function [m1,m2]=match(Iorign,Iorign2)
image(Iorign);
I=single(rgb2gray(Iorign));
image(Iorign2);
I2=single(rgb2gray(Iorign2));
[F1,D1]=vl_sift(I);
[F2,D2]=vl_sift(I2);
% figure;
% subplot(1,2,1);
% imshow(I/256);
% hold on;
% perm = randperm(size(F1,2));
% sel=perm(1:100);
% h1=vl_plotframe(F1(:,sel));
% h2=vl_plotframe(F1(:,sel));
% set(h1,'color','k','linewidth',3);
% set(h2,'color','y','linewidth',2);
% h3=vl_plotsiftdescriptor(D1(:,sel),F1(:,sel));
% set(h3,'color','g');
% subplot(1,2,2);
% imshow(I2/256);
% hold on;
% perm = randperm(size(F2,2));
% sel=perm(1:200);
% h1=vl_plotframe(F2(:,sel));
% h2=vl_plotframe(F2(:,sel));
% set(h1,'color','k','linewidth',3);
% set(h2,'color','y','linewidth',2);
[matches,scores]=vl_ubcmatch(D1,D2);
m1=F1(1:2,matches(1,:));
m2=F2(1:2,matches(2,:));
% m2(1,:)=m2(1,:)+size(I,2)*ones(1,size(m2,2));
X=[m1(1,:);m2(1,:)];
Y=[m1(2,:);m2(2,:)];
% c=[I I2];
% imshow(c,[]);
% hold on;
% plot(X(1,:),Y(1,:),'o');
% plot(X(2,:),Y(2,:),'o');
% line(X(:,1:1:100),Y(:,1:1:100));
end